/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tnlceozwrkspncxwcaqe";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRubGNlb3p3cmtzcG5jeHdjYXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NTI4NDYsImV4cCI6MjA3ODAyODg0Nn0.iY7t1j9I0cXr6cAYX2vgF-eV1HTj_T_TJRKIfHpsCV8";